name: Deploy GoDoc to GitHub Pages

on:
  push:
    branches:
      - main  # ganti jika branch utamamu bukan 'main'

permissions:
  contents: write

jobs:
  deploy-godoc:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout kode sumber
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Go environment
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'  # Sesuaikan dengan versi Go kamu

      # 3. Install golds (generator dokumentasi statis Go)
      - name: Install golds
        run: go install go101.org/golds@latest

      # 4. Generate dokumentasi statik ke folder output
      - name: Generate static HTML documentation
        run: |
          mkdir -p godoc_html
          golds -gen -dir ./
          mv ./docs/* godoc_html/


      # 5. Deploy ke GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./godoc_html
          keep_files: false
