name: Deploy GoDoc to GitHub Pages

on:
  push:
    branches:
      - main  # atau 'master', sesuaikan dengan cabang utama Anda

permissions:
  contents: write

jobs:
  deploy-godoc:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout kode
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Go
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'  # Sesuaikan dengan versi proyek Anda

      # 3. Install godoc
      - name: Install godoc
        run: go install golang.org/x/tools/cmd/godoc@latest

      # 4. Buat direktori output
      - name: Create output directory
        run: mkdir -p godoc_html

      # 5. Generate dokumentasi HTML statis di root
      - name: Generate static HTML documentation
        run: |
          MODULE_PATH=$(grep ^module go.mod | awk '{print $2}')
          echo "Module path: $MODULE_PATH"
        
          godoc -http=:6060 &
          GODOC_PID=$!
          sleep 5
        
          wget --recursive --no-parent --adjust-extension --convert-links --page-requisites \
            --no-host-directories \
            --cut-dirs=4 \
            --directory-prefix=godoc_html/ \
            http://localhost:6060/pkg/$MODULE_PATH/ || true
        
          kill $GODOC_PID
          touch godoc_html/.nojekyll


      # 6. Deploy ke GitHub Pages root
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./godoc_html
          publish_branch: main       # <- pakai `main`
          destination_dir: .         # <- root, tidak perlu subfolder
          force_orphan: true         # <- membuat root bersih
