name: Generate Vanitydoc Site

on:
  push:
    branches: [main]
    paths:
      - vanitydoc.json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install vanitydoc
        run: go install code.pfad.fr/vanitydoc@latest

      - name: Generate HTML site
        run: vanitydoc vanitydoc.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
